### ISSUE TITLE
setInternet2() error

### ISSUE THREAD

**Issue by varsha-raj** [talgalili/installr#64]
Hi, I've been trying to update my R from version 3.2.0 to the latest (3.3.1) and I get this error:
Error in setInternet2() : use != NA is defunct

Is this a bug in installr that's still in the working. Thanks!

**Comment by talgalili** [comment]
Which version of installr are you using?
(look at sessionInfo() )

**Comment by varsha-raj** [comment]
I'm using your latest version- 0.18.0.

devtools::install_github('talgalili/installr')

**Comment by talgalili** [comment]
That is odd.
Hi @varsha-raj 
Please try installing again:
devtools::install_github('talgalili/installr')

This should now be resolved.

Please let me know so I could close this issue.

Tal

**Comment by varsha-raj** [comment]
Hi Tal, I tried installing installr again- I'm still getting the error in my R console:
![setinternet2_error](https://cloud.githubusercontent.com/assets/15203228/17300604/12ee25a4-57e1-11e6-99ac-f147e43011d2.PNG)

**Comment by varsha-raj** [comment]
However my Rstudio opens without any error.

**Comment by talgalili** [comment]
Your R is R 3.3.1. Your screenshot does not seem to show installr being used. Could you please clear and save your working environment and then start R again?

**Comment by varsha-raj** [comment]
Hey Tal, I'm sorry to bother you again and again. I'm still having no luck. The problem is I get the setInternet2() error the moment I open my RGUI. I tried exiting and opening R again- Here are a few snap shots of my R terminal and R studio:
![setinternet2_error_snap2](https://cloud.githubusercontent.com/assets/15203228/17301990/02d4d2ce-57e8-11e6-8878-54321960be6d.PNG)
![rstudio_error](https://cloud.githubusercontent.com/assets/15203228/17301995/05fe4c82-57e8-11e6-952d-d830719d321f.PNG)

**Comment by talgalili** [comment]
I do not understand your screenshots.

When you *start R*, and do nothing, is everything o.k.?

**Comment by varsha-raj** [comment]
I'm sorry to confuse you. When I open my R terminal and do nothing I get an error:
Error in setInternet2(TRUE) : use != NA is defunct

Enter a frame number, or 0 to exit   

1: .First()
2: setInternet2(TRUE)

I need to enter 0 to exit from this in order to do anything in R terminal. However my Rstudio works fine if I do nothing and by nothing I mean not typing in setInternet2(). Hope this is clear enough.

**Comment by varsha-raj** [comment]
I hate to be the only person having this error- we could probably close this issue for now. I always use R studio and Rstudio opens without any error. It's just that the error in my GUI console was bothering me but I guess I can live with it for now- I guess its some faulty thing happening on my end.

**Comment by talgalili** [comment]
Try running the R gui the following:

```r
list.files()
rm(list=ls(all=TRUE))
save.image()
list.files()
```

Please tell me what you get, and if it solved the problem.

**Comment by varsha-raj** [comment]
Wow, Yes this worked. I do not get the error I was getting any longer. This solved the issue. Thanks so much for the help. I previously tried removed all the previously stored workspace but nothing worked then!!! Anyway thanks a lot for the help :)

**Comment by talgalili** [comment]
You're welcome :)
